module.exports = {
  N_KEY_SEED: 'SUACSSL3UAHUDXKFSNVUZRF5UHPMWZ6BFDTJ7M6USDXIEDNPPQYYYCU3VY',
  N_KEY: 'UDXU4RCSJNZOIQHZNWXHXORDPRTGNJAHAHFRGZNEEJCPQTT2M7NLCNF4',
  NATS_URL: 'nats://nats:4222',
  SUBJECT: 'queue',
}
